/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const DishId = IDL.Nat;
export const Category = IDL.Variant({
  'mains' : IDL.Null,
  'desserts' : IDL.Null,
  'starters' : IDL.Null,
  'drinks' : IDL.Null,
});
export const Dish = IDL.Record({
  'id' : DishId,
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'placed' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'card' : IDL.Null,
  'cash' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const DeliveryAddress = IDL.Record({
  'street' : IDL.Text,
  'postcode' : IDL.Text,
  'city' : IDL.Text,
  'notes' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'dishId' : DishId,
  'unitPrice' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'total' : IDL.Nat,
  'paymentMethod' : PaymentMethod,
  'deliveryFee' : IDL.Nat,
  'createdAt' : Timestamp,
  'reference' : IDL.Text,
  'cardholderName' : IDL.Opt(IDL.Text),
  'address' : DeliveryAddress,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'subtotal' : IDL.Nat,
});
export const PlaceOrderError = IDL.Variant({
  'missingCardholderName' : IDL.Null,
  'unknownDish' : DishId,
  'missingCustomerName' : IDL.Null,
  'missingPhone' : IDL.Null,
  'missingAddress' : IDL.Null,
  'dishUnavailable' : DishId,
  'emptyCart' : IDL.Null,
});
export const UpdateOrderStatusError = IDL.Variant({
  'notFound' : OrderId,
  'invalidTransition' : IDL.Record({
    'to' : OrderStatus,
    'from' : OrderStatus,
  }),
  'unauthorized' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDish' : IDL.Func([DishId], [IDL.Opt(Dish)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listDishes' : IDL.Func([], [IDL.Vec(Dish)], ['query']),
  'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'placeOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        DeliveryAddress,
        IDL.Vec(OrderItem),
        PaymentMethod,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : Order, 'err' : PlaceOrderError })],
      [],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'updateOrderStatus' : IDL.Func(
      [OrderId, OrderStatus],
      [IDL.Variant({ 'ok' : Order, 'err' : UpdateOrderStatusError })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const DishId = IDL.Nat;
  const Category = IDL.Variant({
    'mains' : IDL.Null,
    'desserts' : IDL.Null,
    'starters' : IDL.Null,
    'drinks' : IDL.Null,
  });
  const Dish = IDL.Record({
    'id' : DishId,
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'placed' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({ 'card' : IDL.Null, 'cash' : IDL.Null });
  const Timestamp = IDL.Int;
  const DeliveryAddress = IDL.Record({
    'street' : IDL.Text,
    'postcode' : IDL.Text,
    'city' : IDL.Text,
    'notes' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'dishId' : DishId,
    'unitPrice' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'total' : IDL.Nat,
    'paymentMethod' : PaymentMethod,
    'deliveryFee' : IDL.Nat,
    'createdAt' : Timestamp,
    'reference' : IDL.Text,
    'cardholderName' : IDL.Opt(IDL.Text),
    'address' : DeliveryAddress,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'subtotal' : IDL.Nat,
  });
  const PlaceOrderError = IDL.Variant({
    'missingCardholderName' : IDL.Null,
    'unknownDish' : DishId,
    'missingCustomerName' : IDL.Null,
    'missingPhone' : IDL.Null,
    'missingAddress' : IDL.Null,
    'dishUnavailable' : DishId,
    'emptyCart' : IDL.Null,
  });
  const UpdateOrderStatusError = IDL.Variant({
    'notFound' : OrderId,
    'invalidTransition' : IDL.Record({
      'to' : OrderStatus,
      'from' : OrderStatus,
    }),
    'unauthorized' : IDL.Null,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDish' : IDL.Func([DishId], [IDL.Opt(Dish)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listDishes' : IDL.Func([], [IDL.Vec(Dish)], ['query']),
    'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'placeOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          DeliveryAddress,
          IDL.Vec(OrderItem),
          PaymentMethod,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : Order, 'err' : PlaceOrderError })],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'updateOrderStatus' : IDL.Func(
        [OrderId, OrderStatus],
        [IDL.Variant({ 'ok' : Order, 'err' : UpdateOrderStatusError })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };